<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.Specification" Version="6.1.0" />
    <PackageReference Include="Ardalis.Specification.EntityFrameworkCore" Version="6.1.0" />
    <PackageReference Include="Mapster" Version="7.3.0" />
    <PackageReference Include="Mapster.Core" Version="1.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="7.0.3" />
    <PackageReference Include="Microsoft.Office.Excel" Version="14.0.4760.1000" />
    <PackageReference Include="Microsoft.Office.Interop.Excel" Version="15.0.4795.1001" />
  </ItemGroup>

</Project>
